version: '3'
services:

  frontend:
    image: aiweb-frontend:1.0.0
      #build:
      #context: docker-vue
      #dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - ./docker-vue/src:/app/src
      - ./docker-vue/babel.config.js:/app/babel.config.js
  backend:
    image: aiweb-backend:1.0.0
    #build:
    #context: fastapi
    #dockerfile: Dockerfile
    ports:
      - 8000:80
    restart: unless-stopped
    volumes:
      - ./fastapi/app:/fastapi/app
