version: '3'
services:

  frontend:
    build:
      context: docker-vue
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: unless-stopped

  backend:
    build:
      context: fastapi
      dockerfile: Dockerfile
    ports:
      - 8000:80
    restart: unless-stopped
